updating CI/CD action and workflow files

diff --git a/.github/actions/aml-endpoint-test/action.yaml b/.github/actions/aml-endpoint-test/action.yaml
--- a/.github/actions/aml-endpoint-test/action.yaml
+++ b/.github/actions/aml-endpoint-test/action.yaml
@@ -28,23 +28,33 @@ runs:
         ENDPOINT_FILE=${{ inputs.endpointFile }}
         ENDPOINT_NAME=$(yq -r ".endpoint_name" $ENDPOINT_FILE)
         TEST_DEPLOYMENT_NAME=$(yq -r ".name" $ENDPOINT_FILE)
-
-        run_id=$(az ml batch-endpoint invoke --name $ENDPOINT_NAME --deployment $TEST_DEPLOYMENT_NAME --input ${{ inputs.requestFile }} --input-type uri_file --query name -o tsv) 
-        # TODO: test that response is valid, fail with exit 1 if not
-        status=$(az ml job show -n $run_id --query status -o tsv)
-        echo $status
-        if [[ $status == "Completed" ]]
-        then 
-          echo "Job completed"
-        elif [[ $status == "Running" ]]
-        then 
-          echo "Job is running but not sure if it will fail or will succeed"
         
-        elif [[ $status == "Failed" ]]
-        then 
-          echo "Job failed"
-          exist 1
+        deploymentresource=$(az ml batch-deployment list -e $ENDPOINT_NAME --query "[?contains(name, $TEST_DEPLOYMENT_NAME)].{Name:name}" -otsv)
+        if [[ $deploymentresouce == $TEST_DEPLOYMENT_NAME ]];
+          then
+          echo "found existing deployment to test"
+          run_id=$(az ml batch-endpoint invoke --name $ENDPOINT_NAME --deployment $TEST_DEPLOYMENT_NAME --input ${{ inputs.requestFile }} --input-type uri_file --query name -o tsv) 
+          # TODO: test that response is valid, fail with exit 1 if not
+          status="Queued"
+          while ! [[ $status =~ ^(Failed|Completed|Canceled)$ ]];
+          do
+            sleep 60s
+            echo "Still Queued/ Running"
+            status=$(az ml job show -n $run_id --query status -o tsv)
+            echo $status
+          done
+          if [[ $status == "Completed" ]]
+          then 
+            echo "Job completed"      
+          elif [[ $status == "Failed" ]]
+          then 
+            echo "Job failed"
+            exit 1
+          else
+            echo "Job status not failed nor running nor completed"
+            exit 2
+          fi
         else
-          echo "Job status not failed nor running nor completed"
-          exit 2
+          echo "Existing deployment not found"
+          exit 3
         fi
